### PR TITLE
fix bug: Query.Decode

### PR DESCRIPTION
**Pull request by SunBeau**
i think it's a bug

### CODE REVIEW

**Comment by jackc** [comment]
Do you have an example of the existing code failing? I think it is correct as is. The initial byte of message type and the following 4 bytes for message length are already stripped off by the time the message gets to `Decode`.

**Comment by SunBeau** [comment]
code:
`
func QueryDecodeTest(src []byte) {

	fmt.Printf("1---QueryDecodeTest---src[%#v]\n", string(src))
	var q1 pgproto3.Query
	err := q1.Decode(src)
	fmt.Printf("2---QueryDecodeTest---err[%#v]\n", err)

	/* Test Encode Decode  */
	{
		var q2 pgproto3.Query
		q2.String = "select * from b;"

		data := make([]byte, 0, 1)
		data = q2.Encode(data)
		fmt.Printf("3---QueryDecodeTest---src[%#v]\n", string(data))

		err2 := q2.Decode(data)
		fmt.Printf("4---QueryDecodeTest---err[%#v]\n", err2)
	}
}
`
printf:
`
1---QueryDecodeTest---src["Q\x00\x00\x00\x16select * from a ;\x00"]
2---QueryDecodeTest---err[&pgproto3.invalidMessageFormatErr{messageType:"Query"}]
3---QueryDecodeTest---src["Q\x00\x00\x00\x15select * from b;\x00"]
4---QueryDecodeTest---err[&pgproto3.invalidMessageFormatErr{messageType:"Query"}]
`

**Comment by SunBeau** [comment]
data of src is read by myself from psql.
can encode and decode not be converted to each other？

**Comment by jackc** [comment]
> can encode and decode not be converted to each other？

They can with a small intermediate step. `Encode` produces the entire message including the 5 bytes for message type and size of message. But `Decode` only needs the message body. This is because `Frontend` and `Backend` `Receive()` needs to read the type of the message to determine with type to call `Decode` on and the length of the message to read the message into the byte buffer.

**Pull request closed without merging**
