### PR TITLE
fix: AuthenticationMD5Password AuthType

### PR DESCRIPTION
**Pull request by felixge**
I just finished upgrading my PostgreSQL proxy based on pgproto3, and this was the only problem I encountered.

Thank you so much for all the work you put into pgx and pgproto3, they are truly amazing contributions to the Go and PostgreSQL ecosystem.

### CODE REVIEW

**Comment by kensaggy** [comment]
hey @jackc, is it possible to get this merged?
anything I can do to help you accept this (or a new) PR?

(funny enough like @felixge I am also building a PostgresSQL proxy based on pgproto3 :))

**Comment by felixge** [comment]
> (funny enough like @felixge I am also building a PostgresSQL proxy based on pgproto3 :))

Building custom PG proxies is fun, isn't it : )? Mine is a little gateway that serves fake catalog tables that make clients think the proxy has lots of "databases", which are really just gateways into different servers. Saves users from maintaining tons of connections bookmarks in their clients.

What is your proxy doing?

**Comment by kensaggy** [comment]
That's pretty cool @felixge :) 
Mine is supposed to be sort of a reverse-proxy with custom routing mechanics

@felixge did you manage to work around this somehow? fork, patch and use forked version?

**Comment by felixge** [comment]
@kensaggy yeah, I just added this to the bottom of my `go.mod` to use my fork. This approach means you don't need to rewrite the import paths in your own code.

```
// see https://github.com/jackc/pgproto3/pull/1
replace github.com/jackc/pgproto3/v2 => github.com/felixge/pgproto3/v2 v2.0.0-rc3.0.20190908152906-a90ef7ed5b85
```

**Comment by jackc** [comment]
Sorry for the delay. Somehow I had missed this PR.

**Comment by kensaggy** [comment]
@jackc very much appreciate the quick merge on this :)

For others, since there's no [tagged] version which includes this fix, if you need to use it you can use the specific commit like so:  (if you're using `go mod`)
```bash
go get -u github.com/jackc/pgproto3/v2@7746f22
```

**Pull request merged**
