### PR TITLE
add GSS authentication to pgproto3

### PR DESCRIPTION
**Pull request by otan**
This commits adds the GSS protobufs.

### CODE REVIEW

**Comment by otan** [comment]
Marking as draft right now until we get testing sorted out.

**Comment by jackc** [comment]
Is there some reason for the field name of `Token`? `AuthenticationSASLContinue` and `AuthenticationSASLFinal` have a similar opaque payload field called `Data`. Unless there is a special reason I'd prefer to keep the naming consistent.

Aside from that it looks fine so far.

**Comment by otan** [comment]
> Is there some reason for the field name of Token? 

just what i saw the other library call it :') changed accordingly.

**Comment by otan** [comment]
alright well, this is ready for review!

**Comment by jackc** [comment]
LGTM. Thanks!

**Pull request merged**
